
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.Dados;
import Classes.Utilidades;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lozkillers
 */
public class frmPesquisarCliente extends javax.swing.JDialog {

    private Dados clsdados;
    private DefaultTableModel mTabela;
    private String resposta = "";
    
    public void setDados(Dados clsdados){
        this.clsdados = clsdados;
    }
    public String getReposta(){
        return resposta;
    }
      private void preencherTabela(){
            String titulos[] = {"ID Cli","Nome","Telefone"};
            String registro[] = new String[3];
            mTabela = new DefaultTableModel(null,titulos);
            if(txtpesqcli.getText().equals("")){ 
            for(int i=0; i<clsdados.numeroClientes();i++){
                registro[0] = clsdados.getClientes()[i].getIdCliente();
                registro[1] = clsdados.getClientes()[i].getNome();
                registro[2] = clsdados.getClientes()[i].getTelefone();
                mTabela.addRow(registro);
            }
                tbltabela.setModel(mTabela);
                return;
            }
                  if(radionome.isSelected()){
                  for(int i=0; i<clsdados.numeroClientes();i++){
                  if(clsdados.getClientes()[i].getNome().startsWith(txtpesqcli.getText())){
                  registro[0] = clsdados.getClientes()[i].getIdCliente();
                  registro[1] = clsdados.getClientes()[i].getNome();
                  registro[2] = clsdados.getClientes()[i].getTelefone();
                  mTabela.addRow(registro);
                    }
                }
                tbltabela.setModel(mTabela);
                return;
            }
                  if(radioid.isSelected()){
                   for(int i=0; i<clsdados.numeroClientes();i++){
                  if(clsdados.getClientes()[i].getIdCliente().startsWith(txtpesqcli.getText())){
                  registro[0] = clsdados.getClientes()[i].getIdCliente();
                  registro[1] = clsdados.getClientes()[i].getNome();
                  registro[2] = clsdados.getClientes()[i].getTelefone();
                  mTabela.addRow(registro);
                }
            }
                tbltabela.setModel(mTabela);
        }
          
    }
            
    public frmPesquisarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        bgtipopesq.add(radioid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgtipopesq = new javax.swing.ButtonGroup();
        radioid = new javax.swing.JRadioButton();
        radionome = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltabela = new javax.swing.JTable();
        txtpesqcli = new javax.swing.JTextField();
        btnpesqcli = new javax.swing.JToggleButton();
        btnpesqsair = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        radioid.setSelected(true);
        radioid.setText("IdCli");
        radioid.setToolTipText("idCliente");

        radionome.setText("NomeCli");
        radionome.setToolTipText("NomeCli");
        radionome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radionomeActionPerformed(evt);
            }
        });

        tbltabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltabela);

        txtpesqcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesqcliActionPerformed(evt);
            }
        });

        btnpesqcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_link.png"))); // NOI18N
        btnpesqcli.setToolTipText("Pesquisar Cliente");
        btnpesqcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesqcliActionPerformed(evt);
            }
        });

        btnpesqsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        btnpesqsair.setToolTipText("Sair");
        btnpesqsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesqsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnpesqcli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpesqsair, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(radioid)
                        .addGap(63, 63, 63)
                        .addComponent(radionome)
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtpesqcli)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioid)
                    .addComponent(radionome))
                .addGap(18, 18, 18)
                .addComponent(txtpesqcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpesqcli)
                    .addComponent(btnpesqsair))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        preencherTabela();
        txtpesqcli.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void radionomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radionomeActionPerformed
        // TODO add your handling code here:
        txtpesqcli.setText("");
        txtpesqcli.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radionomeActionPerformed

    private void txtpesqcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesqcliActionPerformed
        // TODO add your handling code here:
        preencherTabela();
        
    }//GEN-LAST:event_txtpesqcliActionPerformed

    private void btnpesqsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesqsairActionPerformed
        // TODO add your handling code here:
        resposta = "";
        dispose();
    }//GEN-LAST:event_btnpesqsairActionPerformed

    private void btnpesqcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesqcliActionPerformed
        // TODO add your handling code here:
        int num = tbltabela.getRowCount();
        if(num ==0){
        resposta = "";
        dispose();
        return;
        }
         for(int i=0; i<num;i++){
             if(tbltabela.isRowSelected(i)){
                    resposta = Utilidades.objectToString(tbltabela.getValueAt(i, 0));
                    dispose();
                    return;
                }
         }
                    resposta = Utilidades.objectToString(tbltabela.getValueAt(0, 0));
                    dispose();
                        
    }//GEN-LAST:event_btnpesqcliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPesquisarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPesquisarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPesquisarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPesquisarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPesquisarCliente dialog = new frmPesquisarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgtipopesq;
    private javax.swing.JToggleButton btnpesqcli;
    private javax.swing.JToggleButton btnpesqsair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioid;
    private javax.swing.JRadioButton radionome;
    private javax.swing.JTable tbltabela;
    private javax.swing.JTextField txtpesqcli;
    // End of variables declaration//GEN-END:variables
}
