/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.Dados;
import Classes.Usuarios;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lozkillers
 */
public class frmusuarios extends javax.swing.JInternalFrame {

   private Dados clsdados;
   private int usuarioatual = 0;
   private boolean cmdNovo =false;
   private DefaultTableModel mTabela;
    public void setDados(Dados clsdados){
        this.clsdados = clsdados;
    }
    public frmusuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtcodusuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmdperfil = new javax.swing.JComboBox<>();
        cmdprimeiro = new javax.swing.JButton();
        cmdanterior = new javax.swing.JButton();
        cmdproximo = new javax.swing.JButton();
        cmdultimo = new javax.swing.JButton();
        cmdnovo = new javax.swing.JButton();
        cmdeditar = new javax.swing.JButton();
        cmdsalvar = new javax.swing.JButton();
        cmdpesquisar = new javax.swing.JButton();
        cmddeletar = new javax.swing.JButton();
        txtsenha = new javax.swing.JPasswordField();
        txtconfsenha = new javax.swing.JPasswordField();
        cmdcancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro Usuário");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Cod Usuário:");

        txtcodusuario.setEnabled(false);

        jLabel2.setText("Nome :");

        txtnome.setEnabled(false);

        jLabel3.setText("Senha : ");

        jLabel4.setText("Conf Senha :");

        jLabel5.setText("Perfil :");

        cmdperfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Perfil", "Adiministrador", "Funcionário" }));
        cmdperfil.setEnabled(false);

        cmdprimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/resultset_first.png"))); // NOI18N
        cmdprimeiro.setToolTipText("Primeiro Cadastro");
        cmdprimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdprimeiroActionPerformed(evt);
            }
        });

        cmdanterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/resultset_previous.png"))); // NOI18N
        cmdanterior.setToolTipText("Cadastro Anterior");
        cmdanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdanteriorActionPerformed(evt);
            }
        });

        cmdproximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/resultset_next.png"))); // NOI18N
        cmdproximo.setToolTipText("Próximo Cadastro");
        cmdproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdproximoActionPerformed(evt);
            }
        });

        cmdultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/resultset_last.png"))); // NOI18N
        cmdultimo.setToolTipText("Último Cadastro");
        cmdultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdultimoActionPerformed(evt);
            }
        });

        cmdnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_go.png"))); // NOI18N
        cmdnovo.setToolTipText("Novo Cadastro");
        cmdnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdnovoActionPerformed(evt);
            }
        });

        cmdeditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_edit.png"))); // NOI18N
        cmdeditar.setToolTipText("Editar Cadastro");
        cmdeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdeditarActionPerformed(evt);
            }
        });

        cmdsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_save.png"))); // NOI18N
        cmdsalvar.setToolTipText("Salvar Cadastro");
        cmdsalvar.setEnabled(false);
        cmdsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsalvarActionPerformed(evt);
            }
        });

        cmdpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_link.png"))); // NOI18N
        cmdpesquisar.setToolTipText("Pesquisar Cadastro");
        cmdpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpesquisarActionPerformed(evt);
            }
        });

        cmddeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_delete.png"))); // NOI18N
        cmddeletar.setToolTipText("Deletar Cadastro");
        cmddeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddeletarActionPerformed(evt);
            }
        });

        txtsenha.setEnabled(false);

        txtconfsenha.setEnabled(false);

        cmdcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        cmdcancelar.setToolTipText("Cancelar Cadastro");
        cmdcancelar.setEnabled(false);
        cmdcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelarActionPerformed(evt);
            }
        });

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabela);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group-profile-users_icon-icons.com_73540 (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtconfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcodusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cmdprimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdproximo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmddeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtcodusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtconfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cmdperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(119, 119, 119))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmddeletar)
                    .addComponent(cmdprimeiro)
                    .addComponent(cmdanterior)
                    .addComponent(cmdproximo)
                    .addComponent(cmdultimo)
                    .addComponent(cmdnovo)
                    .addComponent(cmdeditar)
                    .addComponent(cmdsalvar)
                    .addComponent(cmdcancelar)
                    .addComponent(cmdpesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdnovoActionPerformed
        // TODO add your handling code here:
        cmdprimeiro.setEnabled(false);
        cmdanterior.setEnabled(false);
        cmdproximo.setEnabled(false);
        cmdultimo.setEnabled(false);
        cmdnovo.setEnabled(false);
        cmdeditar.setEnabled(false);
        cmdsalvar.setEnabled(true);
        cmddeletar.setEnabled(false);
        cmdpesquisar.setEnabled(false);
        cmdcancelar.setEnabled(true);
        
        txtcodusuario.setEnabled(true);
        txtnome.setEnabled(true);
        txtsenha.setEnabled(true);
        txtconfsenha.setEnabled(true);
        cmdperfil.setEnabled(true);
        
        txtcodusuario.setText("");
        txtnome.setText("");
        txtsenha.setText("");
        txtconfsenha.setText("");
        cmdperfil.setSelectedIndex(0);
        
        cmdNovo = true;

        txtcodusuario.requestFocusInWindow();
                        
        
    }//GEN-LAST:event_cmdnovoActionPerformed

    private void cmdsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsalvarActionPerformed
        // TODO add your handling code here:
        
        if(txtcodusuario.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digitar o seu código para realizar seu cadastro!");
            txtcodusuario.requestFocusInWindow();
            return;
            
        } if(cmdperfil.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Por favor, selecionar um perfil para realizar seu cadastro!");
            cmdperfil.requestFocusInWindow();
            return;
            
        } if(txtnome.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digitar o seu nome para realizar seu cadastro!");
            txtnome.requestFocusInWindow();
            return;      
        }
        String sSenha = new String (txtsenha.getPassword());
        String confSenha = new String(txtconfsenha.getPassword());
        
        if(sSenha.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digitar a sua senha para realizar seu cadastro!");
            txtsenha.requestFocusInWindow();
            return;
            
        } if (confSenha.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor, confirmar a para realizar seu cadastro!");
            txtsenha.setText("");
            txtconfsenha.requestFocusInWindow();
            return;
        }
        if (!sSenha.equals(confSenha)){
            JOptionPane.showMessageDialog(rootPane, "Confirmação de senha incorreta!");
            txtsenha.setText("");
            txtconfsenha.setText("");
            txtsenha.requestFocusInWindow();
            return;
        }
        
        int poslinha = clsdados.LinhaUsuario(txtcodusuario.getText());
        if(cmdNovo){
            if (poslinha != -1){
                JOptionPane.showMessageDialog(rootPane, "Este usuário já está cadastrado");
                txtcodusuario.requestFocusInWindow();
                return;
            }
        }else{
            if(poslinha == -1){
                JOptionPane.showMessageDialog(rootPane, "Este usuário não está cadastrado");
                txtcodusuario.requestFocusInWindow();
                return;
            }
        }
        
       Usuarios Musuario = new Usuarios(txtcodusuario.getText()
               ,txtnome.getText(), 
               sSenha, 
               cmdperfil.getSelectedIndex());
       
       String msg;
       if(cmdNovo){
         msg = clsdados.CadUsuarios(Musuario);
       }else{ 
       msg = clsdados.editar(Musuario, poslinha);   
       }
       JOptionPane.showMessageDialog(rootPane, msg);
        
        
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdnovo.setEnabled(true);
        cmdeditar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmddeletar.setEnabled(true);
        cmdpesquisar.setEnabled(true);
        cmdcancelar.setEnabled(false);
        
        txtcodusuario.setEnabled(false);
        txtnome.setEnabled(false);
        txtsenha.setEnabled(false);
        txtconfsenha.setEnabled(false);
        cmdperfil.setEnabled(false);
        
        txtnome.requestFocusInWindow();
        
        preencherTabela();
        
        
        

    }//GEN-LAST:event_cmdsalvarActionPerformed

    private void cmddeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmddeletarActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente deletar esse cadastro?");
        if(resposta !=0){
            return;
        }
          String msg;
          msg = clsdados.deletarUsuario(usuarioatual);
          JOptionPane.showMessageDialog(rootPane, msg);
          usuarioatual = 0;
          mostrarRegistro();
           preencherTabela();
    }//GEN-LAST:event_cmddeletarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        mostrarRegistro();
        preencherTabela();
    
    }//GEN-LAST:event_formInternalFrameOpened
private void mostrarRegistro(){
    
        txtcodusuario.setText(clsdados.getUsuarios()[usuarioatual].getCodusuario());
        txtnome.setText(clsdados.getUsuarios()[usuarioatual].getNome());
        txtsenha.setText(clsdados.getUsuarios()[usuarioatual].getSenha());
        txtconfsenha.setText(clsdados.getUsuarios()[usuarioatual].getSenha());
        cmdperfil.setSelectedIndex(clsdados.getUsuarios()[usuarioatual].getPerfil());
}
        private void preencherTabela(){
            String titulos[] = {"CodUsuário","Nome","Perfil"};
            String registro[] = new String[3];
            mTabela = new DefaultTableModel(null,titulos);
            for(int i=0; i<clsdados.numeroUsuarios(); i++){
                registro[0] = clsdados.getUsuarios()[i].getCodusuario();
                registro[1] = clsdados.getUsuarios()[i].getNome();
                registro[2] = perfil(+ clsdados.getUsuarios()[i].getPerfil());
                mTabela.addRow(registro);
                
            }
            tblTabela.setModel(mTabela);
        } 
        private String perfil(int idperfil){
            if(idperfil == 1){
                return "Administrador";
            }else{
                 return "Funcionário";
            }
        }
    private void cmdeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdeditarActionPerformed
        // TODO add your handling code here:
        
        cmdprimeiro.setEnabled(false);
        cmdanterior.setEnabled(false);
        cmdproximo.setEnabled(false);
        cmdultimo.setEnabled(false);
        cmdnovo.setEnabled(false);
        cmdeditar.setEnabled(false);
        cmdsalvar.setEnabled(true);
        cmddeletar.setEnabled(false);
        cmdpesquisar.setEnabled(false);
        cmdcancelar.setEnabled(true);
        
        txtcodusuario.setEnabled(true);
        txtnome.setEnabled(true);
        txtsenha.setEnabled(true);
        txtconfsenha.setEnabled(true);
        cmdperfil.setEnabled(true);
        
        cmdNovo = false;

        txtnome.requestFocusInWindow();
        

    }//GEN-LAST:event_cmdeditarActionPerformed

    private void cmdprimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdprimeiroActionPerformed
        // TODO add your handling code here:
        usuarioatual = 0;
        mostrarRegistro();
    }//GEN-LAST:event_cmdprimeiroActionPerformed

    private void cmdultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdultimoActionPerformed
        // TODO add your handling code here:
        usuarioatual = clsdados.numeroUsuarios()-1;
        mostrarRegistro();
        
    }//GEN-LAST:event_cmdultimoActionPerformed

    private void cmdproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdproximoActionPerformed
        // TODO add your handling code here:
        usuarioatual++;
        if(usuarioatual == clsdados.numeroUsuarios()){
            usuarioatual = 0;
        }
        mostrarRegistro();
    }//GEN-LAST:event_cmdproximoActionPerformed

    private void cmdanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdanteriorActionPerformed
        // TODO add your handling code here:
        usuarioatual--;
        if(usuarioatual == -1){
            usuarioatual = clsdados.numeroUsuarios()-1;
        }
        mostrarRegistro();
    }//GEN-LAST:event_cmdanteriorActionPerformed

    private void cmdcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelarActionPerformed
        // TODO add your handling code here:
        cmdprimeiro.setEnabled(true);
        cmdanterior.setEnabled(true);
        cmdproximo.setEnabled(true);
        cmdultimo.setEnabled(true);
        cmdnovo.setEnabled(true);
        cmdeditar.setEnabled(true);
        cmdsalvar.setEnabled(false);
        cmddeletar.setEnabled(true);
        cmdpesquisar.setEnabled(true);
        cmdcancelar.setEnabled(false);
        
        txtcodusuario.setEnabled(false);
        txtnome.setEnabled(false);
        txtsenha.setEnabled(false);
        txtconfsenha.setEnabled(false);
        cmdperfil.setEnabled(false);
        
        txtcodusuario.setText("");
        txtnome.setText("");
        txtsenha.setText("");
        txtconfsenha.setText("");
        cmdperfil.setSelectedIndex(0);
        
         mostrarRegistro();
        
        
    }//GEN-LAST:event_cmdcancelarActionPerformed

    private void cmdpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpesquisarActionPerformed
        // TODO add your handling code here:
        String usuario = JOptionPane.showInputDialog("Favor, inserir o código do usuário");
        if(usuario.equals("")){
            return;
        }
        int pos = clsdados.LinhaUsuario(usuario);
        if(pos == -1){
            JOptionPane.showMessageDialog(rootPane,"Este usuário não existe");
           return;
        }
           usuarioatual = pos;
            mostrarRegistro();
        
    }//GEN-LAST:event_cmdpesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdanterior;
    private javax.swing.JButton cmdcancelar;
    private javax.swing.JButton cmddeletar;
    private javax.swing.JButton cmdeditar;
    private javax.swing.JButton cmdnovo;
    private javax.swing.JComboBox<String> cmdperfil;
    private javax.swing.JButton cmdpesquisar;
    private javax.swing.JButton cmdprimeiro;
    private javax.swing.JButton cmdproximo;
    private javax.swing.JButton cmdsalvar;
    private javax.swing.JButton cmdultimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtcodusuario;
    private javax.swing.JPasswordField txtconfsenha;
    private javax.swing.JTextField txtnome;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
